[versions]
minecraft = "26.1-pre-1"
fabric-loader = "0.18.4"
neoforge-loader = "10.0.10"
fabric-api = "0.143.12+26.1"
modmenu = "18.0.0-alpha.5"

yumi-mc-foundation = "1.0.0-beta.2+26.1-snapshot-6"

# Gradle
gradle-licenser = "2.2.+"
gradle-loom = "1.15.+"
gradle-lambdamcdev = "1.9.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# Dependencies
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }

# Gradle
gradle-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "gradle-licenser" }
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }

[plugins]
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "gradle-licenser" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "gradle-loom" }
lambdamcdev = { id = "dev.lambdaurora.mcdev", version.ref = "gradle-lambdamcdev" }
