[versions]
minecraft = "1.21.10"
fabric-loader = "0.17.2"
neoforge-loader = "10.0.10"
fabric-api = "0.133.13+1.21.9"
mappings-yalmm = "2"
modmenu="15.0.0-beta.1"

yumi-mc-foundation = "1.0.0-beta.1+1.21.10"

# Gradle
gradle-licenser = "2.2.+"
gradle-loom = "1.13.+"
gradle-lambdamcdev = "1.8.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# Dependencies
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }

# Gradle
gradle-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "gradle-licenser" }
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }
