[versions]
minecraft = "1.21.5"
fabric-loader = "0.16.10"
fabric-api = "0.119.5+1.21.5"
mappings-yalmm = "14"
modmenu="14.0.0-rc.2"

yumi-commons = "1.0.0-alpha.10"

# Gradle
gradle-licenser = "2.1.+"
gradle-loom = "1.10.+"
gradle-lambdamcdev = "1.2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# Dependencies
yumi-commons-core = { module = "dev.yumi.commons:yumi-commons-core", version.ref = "yumi-commons" }
yumi-commons-collections = { module = "dev.yumi.commons:yumi-commons-collections", version.ref = "yumi-commons" }
yumi-commons-event = { module = "dev.yumi.commons:yumi-commons-event", version.ref = "yumi-commons" }

# Gradle
gradle-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "gradle-licenser" }
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }
