name: Gradle Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --parallel --stacktrace

      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./build/libs/

      # The USERNAME and PASSWORD need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages and other Mavens
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish --stacktrace
        env:
          BRANCH_NAME: ${{ github.ref }}
          RUN_COUNT: ${{ github.run_number }}
          REPO_NAME: ${{ github.repository }}
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPRUCEUI_MAVEN: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
